name: UHC
author: Saikatsune
version: 1.0.0-B
main: net.saikatsune.uhc.Game

commands:
  worldeditor:
    permission: uhc.host
  configeditor:
    permission: uhc.host
  bordereditor:
    permission: uhc.host
  scenarioseditor:
    permission: uhc.host
  setup:
    permission: uhc.host
  mutechat:
    permission: uhc.host
  start:
    permission: uhc.host
  time:
    permission: uhc.host
  heal:
    permission: uhc.host
  rates:
    permission: uhc.host
    aliases: [rate]
  staff:
    permission: uhc.host
    aliases: [mod]
  latescatter:
    aliases: [scatter]
  respawn:
    permission: uhc.host
    aliases: [revive]
  alerts:
    permission: uhc.host
    aliases: [togglealerts]
  whitelist:
    permission: uhc.host
    aliases: [wl]
  starterfood:
    permission: uhc.host
  giveall:
    permission: uhc.host
  helpopmute:
    permission: uhc.host
  helpopunmute:
    permission: uhc.host
  forceenable:
    permission: uhc.host
  host:
    permission: uhc.host
  disqualify:
    permission: uhc.host
  practice:
    aliases: [prac, arena, a]
  health:
    aliases: [h]
  teamchat:
    aliases: [tc]
  sendcoords:
    aliases: [sc]
  backpack:
    aliases: [bp]
  killstop:
    aliases: [kt]
  team:
  list:
  helpop:
  config:
  scenarios:
  stats: